# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ht5ISlYohBI9ODsiAq6KHSyXwWaxGS5
"""

# --- INSTALL (DeepFace + dependencies) ---
!pip install -q deepface==0.0.96

import os
import pandas as pd
from deepface import DeepFace
from google.colab import files

BASE = "/content/face_db"
os.makedirs(BASE, exist_ok=True)

def make_person_folder(name: str):
    path = os.path.join(BASE, name)
    os.makedirs(path, exist_ok=True)
    return path

# Example: create folders (change names to your project members / dataset people)
people = ["Sateyender Prajapati", "Aditiya"]   # <- edit these names
for p in people:
    print("created:", make_person_folder(p))

print("Upload images now (you can upload many). After upload, move them into the right person folder.")
uploaded = files.upload()

# move uploaded files into the first person's folder by default (you can adjust below)
# (this is just a quick starter; you can reorganize after upload)
first_person = people[0]
dest = os.path.join(BASE, first_person)
for filename in uploaded.keys():
    src = "/content/" + filename
    dst = os.path.join(dest, filename)
    if os.path.exists(src):
        os.replace(src, dst)

print("Files placed into:", dest)
!find /content/face_db -maxdepth 2 -type f -print

print("Upload two images to compare (any names).")
pair = files.upload()
paths = ["/content/" + fn for fn in pair.keys()]

if len(paths) < 2:
    print("Error: Please upload two images for comparison to proceed.")
else:
    result = DeepFace.verify(img1_path=paths[0], img2_path=paths[1])
    display(result)

print("Upload the query image (the face you want to identify).")
q = files.upload()
query_path = "/content/" + list(q.keys())[0]

df = DeepFace.find(img_path=query_path, db_path=BASE, enforce_detection=False)
df[0].head(), df[0].tail()

import cv2
from matplotlib import pyplot as plt

top = df[0].iloc[0] if df and not df[0].empty else None
print("Top match:", None if top is None else top["identity"])
print("Distance:", None if top is None else top["distance"])

img = cv2.imread(query_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,5))
plt.imshow(img_rgb)
plt.axis("off")
plt.title("Query image" + ("" if top is None else f"\nPredicted: {os.path.basename(os.path.dirname(top['identity']))} (dist={top['distance']:.3f})"))
plt.show()